name: Miranda's Blog
description: >
    Miranda's Blog
about: >
    More cleverness here.
master_repo: false
url: "https://0hh1miranda.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Miranda
  avatar:         "https://avatars0.githubusercontent.com/u/25985177?s=400&u=d5045010e87e561a56646765551e38594f912d0b&v=4"
  email:          "miranda.fullerton@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter: 0hh1miranda
  github: https://github.com/0hh1miranda
  stackexchange:
  linkedin: https://www.linkedin.com/in/mirandafullerton
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
